### ISSUE TITLE
Pinbelegung unklar

### ISSUE THREAD

**Issue by PeterDHabermehl** [elektrofuzzis/ftExtender#1]
Hallo zusammen,
bei der Pinbelegung muss man ein bisschen raten - die Zeichnungen der Pinbelegung bieten keine Orientierungshilfe. Schaue ich auf Stecker oder Buchse, von vorn / hinten?

Gruß
Peter

**Comment by elektrofuzzis** [comment]
Hallo Peter,

am der Buchsenleiste an die Du Dein Flachbandkabel crimpst, gibt es auf einer Seite einen Pfeil. Dieser Pfeil zeigt auf PIN 1 - normalerweise crimpt man dahin die rote Ader. Dann hat dein Flachbandkabel automatisch die richtige Reihenfolge 1,2,3... Das passt dann zu den Angaben auf dem Schaltplan.

Gruss 

Stefan

Am 26. März 2019 00:47:00 MEZ schrieb Peter Habermehl <notifications@github.com>:
>Hallo zusammen,>
>bei der Pinbelegung muss man ein bisschen raten - die Zeichnungen der
>Pinbelegung bieten keine Orientierungshilfe. Schaue ich auf Stecker
>oder Buchse, von vorn / hinten?>
>>
>Gruß>
>Peter>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/elektrofuzzis/ftExtender/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by PeterDHabermehl** [comment]
Ja.. genau.. oh Mann, manchmal sieht man den Wald vor lauter Bäumen nicht - 
ich habe die Führungsnut gesucht... Elektronik-Hardware sollte halt lieber 
jemand Anderes machen :-)

Danke 
Peter


Am Donnerstag, 28. März 2019, 17:59:15 CET schrieb elektrofuzzis:
> Hallo Peter,
> 
> am der Buchsenleiste an die Du Dein Flachbandkabel crimpst, gibt es auf
> einer Seite einen Pfeil. Dieser Pfeil zeigt auf PIN 1 - normalerweise
> crimpt man dahin die rote Ader. Dann hat dein Flachbandkabel automatisch
> die richtige Reihenfolge 1,2,3... Das passt dann zu den Angaben auf dem
> Schaltplan.
 
> Gruss 
> 
> Stefan
> 
> Am 26. März 2019 00:47:00 MEZ schrieb Peter Habermehl
> <notifications@github.com>:
> >Hallo zusammen,>
> >bei der Pinbelegung muss man ein bisschen raten - die Zeichnungen der
> >Pinbelegung bieten keine Orientierungshilfe. Schaue ich auf Stecker
> >oder Buchse, von vorn / hinten?>
> >
> >>
> >
> >Gruß>
> >Peter>
